source "http://rubygems.org"

gem 'gmail'
gem 'googlevoiceapi'
gem 'commander'

group :development do
  gem "shoulda", ">= 0"
  gem "bundler", "~> 1.0.0"
  gem "jeweler", "~> 1.6.4"
  gem "rcov", ">= 0"
end

group :test do
  gem "rspec"
end
